backend:
  name: github
  repo: asantoss/web-dev-portfolio
  branch: main
  auth_scope: repo
  base_url: https://alexsantos.dev
  auth_endpoint: api/auth
  site_domain: https://alexsantos.dev

media_folder: 'static/uploads'
public_folder: '/uploads'

collections:
  - name: 'posts'
    label: 'Posts'
    folder: 'src/posts'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
