# For more details, read this: https://coolify.io/docs/github-actions
name: Production Deploy
on:
  push:
    branches: [$default-branch]
  repository_dispatch:
    types: [sveltia-cms-publish]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: 'andrasbacsai/github-actions-with-coolify'

jobs:
  amd64:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Trigger deployment with appropriate tag
      - name: Trigger Coolify deployment
        run: |
          # Regular deployment without tag
          DEPLOY_URL="${{ secrets.COOLIFY_URL }}/api/v1/deploy?uuid=${{ secrets.COOLIFY_RESOURCE_ID }}&force=false"
          curl --request GET "$DEPLOY_URL" \
          --header 'Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}'
